metadata:
- appName: ''
  dataId: seata.properties
  desc: ''
  group: SEATA_GROUP
  type: properties
- appName: ''
  dataId: application.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: gateway.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-course.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-system.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
- appName: ''
  dataId: service-user.properties
  desc: ''
  group: DEFAULT_GROUP
  type: properties
