version: "3.8"

networks:
  edu-net:
    name: edu-net
    driver: bridge

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/gateway.jar
    container_name: edu-gateway
    restart: always
    ports:
      - "8080:7700"
    networks:
      - edu-net

  service-system:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/system.jar
    container_name: edu-service-system
    restart: always
    ports:
      - "8710:7710"
    networks:
      - edu-net

  service-user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/user.jar
    container_name: edu-service-user
    restart: always
    ports:
      - "8720:7720"
    networks:
      - edu-net

  service-course:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/course.jar
    container_name: edu-service-course
    restart: always
    ports:
      - "8730:7730"
    networks:
      - edu-net
