version: "3.8"

networks:
  edu-net:
    external: true

services:
  frontend-nginx:
    image: nginx:alpine
    container_name: edu-frontend
    restart: always
    ports:
      - "6080:80"
      - "6081:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/admin:/usr/share/nginx/html/admin:ro
      - ./dist/web:/usr/share/nginx/html/web:ro
    networks:
      - edu-net
