version: "3.8"

networks:
  edu-net:
    external: true

services:
  frontend-nginx:
    image: ${REGISTRY:-crpi-p83fit5o5eksva55.cn-beijing.personal.cr.aliyuncs.com}/kingtiger-edu/frontend:${IMAGE_TAG:-latest}
    container_name: edu-frontend
    restart: always
    ports:
      - "6080:80"
      - "6081:81"
    networks:
      - edu-net
