# datasource
spring.datasource.druid.url=${spring.datasource.base.url}_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true

# job
xxl.job.executor.port=7712
xxl.job.executor.logpath=${user.home}/logs/system/xxl-job
xxl.job.executor.appname=system-executor

# mybatis
mybatis.mapper-locations=classpath:mybatis/*.xml
mybatis.type-aliases-package=com.roncoo.education.system.service.dao.impl.mapper.bean.entity

# logfile
management.endpoint.logfile.external-file=${user.home}/logs/system/info.log

# springdoc
springdoc.packages-to-scan=com.roncoo.education.system.service
