# datasource
spring.datasource.druid.url=${spring.datasource.base.url}_course?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true

# job
xxl.job.executor.port=7732
xxl.job.executor.logpath=${user.home}/logs/course/xxl-job
xxl.job.executor.appname=course-executor

# mybatis
mybatis.mapper-locations=classpath:mybatis/*.xml
mybatis.type-aliases-package=com.roncoo.education.course.service.dao.impl.mapper.bean.entity

# logfile
management.endpoint.logfile.external-file=${user.home}/logs/course/info.log

# springdoc
springdoc.packages-to-scan=com.roncoo.education.course.service
